apiVersion: apps/v1
kind: Deployment
metadata:
  name: furniture-deployment
  labels:
    app: furniture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: furniture
  template:
    metadata:
      labels:
        app: furniture
    spec:
      containers:
      - name: furniture
        image: 851725486612.dkr.ecr.us-west-2.amazonaws.com/shopping-site-furniture:c7766ce77e5f6686a0ebf8a186106c5ce9778dde
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: furniture-service
  labels:
    app: furniture
spec:
  type: ClusterIP
  selector:
    app: furniture
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
