
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
        image: 767397833358.dkr.ecr.us-west-2.amazonaws.com/shopping-site-backend:09adb7c42a7f2a8f27b2eab1bfbcef71d0159bfb
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP